/*********************************************************************\
 *    __   _ _____ _______ _     _  ______ _     _ ______ __   __    *
 *    | \  |   |   |       |_____| |_____/ |     | |_____]  \_/      *
 *    |  \_| __|__ |_____  |     | |    \_ |_____| |_____]   |       *
 *                             nich ruby                             *
 *                                                                   *
 *             Copyright (C) 2020-2024 Alexander Nicholi             *
 *                    Released under BSD-2-Clause                    *
\*********************************************************************/

/* DEFINITION MODULE */

#ifndef INC__CONST_BATTLE_ANIM_H
#define INC__CONST_BATTLE_ANIM_H

/* This header contains constants for battle animations. */

/* particle IDs */
enum /* anim_tag */
{
	ANIM_TAG_BONE = 10000,
	ANIM_TAG_SPARK,
	ANIM_TAG_PENCIL,
	ANIM_TAG_AIR_WAVE,
	ANIM_TAG_UNUSED_ORB,
	ANIM_TAG_SWORD,
	ANIM_TAG_SEED,
	ANIM_TAG_UNUSED_EXPLOSION,
	ANIM_TAG_UNUSED_PINK_ORB,
	ANIM_TAG_GUST,
	ANIM_TAG_ICE_CUBE,
	ANIM_TAG_SPARK_2,
	ANIM_TAG_UNUSED_ORANGE,
	ANIM_TAG_YELLOW_BALL,
	ANIM_TAG_LOCK_ON,
	ANIM_TAG_TIED_BAG,
	ANIM_TAG_BLACK_SMOKE,
	ANIM_TAG_BLACK_BALL,
	ANIM_TAG_CONVERSION,
	ANIM_TAG_UNUSED_GLASS,
	ANIM_TAG_HORN_HIT,
	ANIM_TAG_UNUSED_HIT,
	ANIM_TAG_UNUSED_HIT_2,
	ANIM_TAG_UNUSED_BLUE_SHARDS,
	ANIM_TAG_UNUSED_CLOSING_EYE,
	ANIM_TAG_UNUSED_WAVING_HAND,
	ANIM_TAG_UNUSED_HIT_DUPLICATE,
	ANIM_TAG_LEER,
	ANIM_TAG_UNUSED_BLUE_BURST,
	ANIM_TAG_SMALL_EMBER,
	ANIM_TAG_GRAY_SMOKE,
	ANIM_TAG_BLUE_STAR,
	ANIM_TAG_UNUSED_BUBBLE_BURST,
	ANIM_TAG_FIRE,
	ANIM_TAG_UNUSED_SPINNING_FIRE,
	ANIM_TAG_FIRE_PLUME,
	ANIM_TAG_UNUSED_LIGHTNING,
	ANIM_TAG_LIGHTNING,
	ANIM_TAG_UNUSED_CLAW_SLASH,
	ANIM_TAG_CLAW_SLASH,
	ANIM_TAG_UNUSED_SCRATCH,
	ANIM_TAG_UNUSED_SCRATCH_2,
	ANIM_TAG_UNUSED_BUBBLE_BURST_2,
	ANIM_TAG_ICE_CHUNK,
	ANIM_TAG_UNUSED_GLASS_2,
	ANIM_TAG_UNUSED_PINK_HEART,
	ANIM_TAG_UNUSED_SAP_DRIP,
	ANIM_TAG_UNUSED_SAP_DRIP_2,
	ANIM_TAG_SPARKLE_1,
	ANIM_TAG_SPARKLE_2,
	ANIM_TAG_HUMANOID_FOOT,
	ANIM_TAG_UNUSED_MONSTER_FOOT,
	ANIM_TAG_UNUSED_HUMANOID_HAND,
	ANIM_TAG_NOISE_LINE,
	ANIM_TAG_UNUSED_YELLOW_UNK,
	ANIM_TAG_UNUSED_RED_FIST,
	ANIM_TAG_SLAM_HIT,
	ANIM_TAG_UNUSED_RING,
	ANIM_TAG_ROCKS,
	ANIM_TAG_UNUSED_Z,
	ANIM_TAG_UNUSED_YELLOW_UNK_2,
	ANIM_TAG_UNUSED_AIR_SLASH,
	ANIM_TAG_UNUSED_SPINNING_GREEN_ORBS,
	ANIM_TAG_LEAF,
	ANIM_TAG_FINGER,
	ANIM_TAG_POISON_POWDER,
	ANIM_TAG_UNUSED_BROWN_TRIANGLE,
	ANIM_TAG_SLEEP_POWDER,
	ANIM_TAG_STUN_SPORE,
	ANIM_TAG_UNUSED_POWDER,
	ANIM_TAG_SPARKLE_3,
	ANIM_TAG_SPARKLE_4,
	ANIM_TAG_MUSIC_NOTES,
	ANIM_TAG_DUCK,
	ANIM_TAG_MUD_SAND,
	ANIM_TAG_ALERT,
	ANIM_TAG_UNUSED_BLUE_FLAMES,
	ANIM_TAG_UNUSED_BLUE_FLAMES_2,
	ANIM_TAG_UNUSED_SHOCK,
	ANIM_TAG_SHOCK,
	ANIM_TAG_UNUSED_BELL,
	ANIM_TAG_UNUSED_PINK_GLOVE,
	ANIM_TAG_UNUSED_BLUE_LINES,
	ANIM_TAG_UNUSED_IMPACT,
	ANIM_TAG_UNUSED_IMPACT_2,
	ANIM_TAG_UNUSED_RETICLE,
	ANIM_TAG_BREATH,
	ANIM_TAG_ANGER,
	ANIM_TAG_UNUSED_SNOWBALL,
	ANIM_TAG_UNUSED_VINE,
	ANIM_TAG_UNUSED_SWORD,
	ANIM_TAG_UNUSED_CLAPPING,
	ANIM_TAG_UNUSED_RED_TUBE,
	ANIM_TAG_AMNESIA,
	ANIM_TAG_UNUSED_STRING,
	ANIM_TAG_UNUSED_PENCIL,
	ANIM_TAG_UNUSED_PETAL,
	ANIM_TAG_BENT_SPOON,
	ANIM_TAG_UNUSED_WEB,
	ANIM_TAG_MILK_BOTTLE,
	ANIM_TAG_COIN,
	ANIM_TAG_UNUSED_CRACKED_EGG,
	ANIM_TAG_UNUSED_HATCHED_EGG,
	ANIM_TAG_UNUSED_FRESH_EGG,
	ANIM_TAG_UNUSED_FANGS,
	ANIM_TAG_UNUSED_EXPLOSION_2,
	ANIM_TAG_UNUSED_EXPLOSION_3,
	ANIM_TAG_UNUSED_WATER_DROPLET,
	ANIM_TAG_UNUSED_WATER_DROPLET_2,
	ANIM_TAG_UNUSED_SEED,
	ANIM_TAG_UNUSED_SPROUT,
	ANIM_TAG_UNUSED_RED_WAND,
	ANIM_TAG_UNUSED_PURPLE_GREEN_UNK,
	ANIM_TAG_UNUSED_WATER_COLUMN,
	ANIM_TAG_UNUSED_MUD_UNK,
	ANIM_TAG_RAIN_DROPS,
	ANIM_TAG_UNUSED_FURY_SWIPES,
	ANIM_TAG_UNUSED_VINE_2,
	ANIM_TAG_UNUSED_TEETH,
	ANIM_TAG_UNUSED_BONE,
	ANIM_TAG_UNUSED_WHITE_BAG,
	ANIM_TAG_UNUSED_UNKNOWN,
	ANIM_TAG_UNUSED_PURPLE_CORAL,
	ANIM_TAG_UNUSED_PURPLE_DROPLET,
	ANIM_TAG_UNUSED_SHOCK_2,
	ANIM_TAG_UNUSED_CLOSING_EYE_2,
	ANIM_TAG_UNUSED_METAL_BALL,
	ANIM_TAG_UNUSED_MONSTER_DOLL,
	ANIM_TAG_UNUSED_WHIRLWIND,
	ANIM_TAG_UNUSED_WHIRLWIND_2,
	ANIM_TAG_UNUSED_EXPLOSION_4,
	ANIM_TAG_UNUSED_EXPLOSION_5,
	ANIM_TAG_UNUSED_TONGUE,
	ANIM_TAG_UNUSED_SMOKE,
	ANIM_TAG_UNUSED_SMOKE_2,
	ANIM_TAG_IMPACT,
	ANIM_TAG_CIRCLE_IMPACT,
	ANIM_TAG_SCRATCH,
	ANIM_TAG_CUT,
	ANIM_TAG_SHARP_TEETH,
	ANIM_TAG_RAINBOW_RINGS,
	ANIM_TAG_ICE_CRYSTALS,
	ANIM_TAG_ICE_SPIKES,
	ANIM_TAG_HANDS_AND_FEET,
	ANIM_TAG_MIST_CLOUD,
	ANIM_TAG_CLAMP,
	ANIM_TAG_BUBBLE,
	ANIM_TAG_ORBS,
	ANIM_TAG_WATER_IMPACT,
	ANIM_TAG_WATER_ORB,
	ANIM_TAG_POISON_BUBBLE,
	ANIM_TAG_TOXIC_BUBBLE,
	ANIM_TAG_SPIKES,
	ANIM_TAG_HORN_HIT_2,
	ANIM_TAG_AIR_WAVE_2,
	ANIM_TAG_SMALL_BUBBLES,
	ANIM_TAG_ROUND_SHADOW,
	ANIM_TAG_SUNLIGHT,
	ANIM_TAG_SPORE,
	ANIM_TAG_FLOWER,
	ANIM_TAG_RAZOR_LEAF,
	ANIM_TAG_NEEDLE,
	ANIM_TAG_WHIRLWIND_LINES,
	ANIM_TAG_GOLD_RING,
	ANIM_TAG_PURPLE_RING,
	ANIM_TAG_BLUE_RING,
	ANIM_TAG_GREEN_LIGHT_WALL,
	ANIM_TAG_BLUE_LIGHT_WALL,
	ANIM_TAG_RED_LIGHT_WALL,
	ANIM_TAG_GRAY_LIGHT_WALL,
	ANIM_TAG_ORANGE_LIGHT_WALL,
	ANIM_TAG_BLACK_BALL_2,
	ANIM_TAG_PURPLE_GAS_CLOUD,
	ANIM_TAG_SPARK_H,
	ANIM_TAG_YELLOW_STAR,
	ANIM_TAG_LARGE_FRESH_EGG,
	ANIM_TAG_SHADOW_BALL,
	ANIM_TAG_LICK,
	ANIM_TAG_UNUSED_VOID_LINES,
	ANIM_TAG_STRING,
	ANIM_TAG_STRING_DOT,
	ANIM_TAG_WEB,
	ANIM_TAG_UNUSED_LIGHTBULB,
	ANIM_TAG_SLASH,
	ANIM_TAG_FOCUS_ENERGY,
	ANIM_TAG_SPHERE_TO_CUBE,
	ANIM_TAG_TENDRILS,
	ANIM_TAG_EYE,
	ANIM_TAG_WHITE_SHADOW,
	ANIM_TAG_TEAL_ALERT,
	ANIM_TAG_OPENING_EYE,
	ANIM_TAG_ROUND_WHITE_HALO,
	ANIM_TAG_FANG_ATTACK,
	ANIM_TAG_PURPLE_HAND_OUTLINE,
	ANIM_TAG_MOON,
	ANIM_TAG_SPARKLE_5,
	ANIM_TAG_SPIRAL,
	ANIM_TAG_SNORE_Z,
	ANIM_TAG_EXPLOSION,
	ANIM_TAG_NAIL,
	ANIM_TAG_GHOSTLY_SPIRIT,
	ANIM_TAG_WARM_ROCK,
	ANIM_TAG_BREAKING_EGG,
	ANIM_TAG_THIN_RING,
	ANIM_TAG_UNUSED_PUNCH_IMPACT,
	ANIM_TAG_BELL,
	ANIM_TAG_MUSIC_NOTES_2,
	ANIM_TAG_SPEED_DUST,
	ANIM_TAG_TORN_METAL,
	ANIM_TAG_THOUGHT_BUBBLE,
	ANIM_TAG_MAGENTA_HEART,
	ANIM_TAG_ELECTRIC_ORBS,
	ANIM_TAG_CIRCLE_OF_LIGHT,
	ANIM_TAG_ELECTRICITY,
	ANIM_TAG_FINGER_2,
	ANIM_TAG_MOVEMENT_WAVES,
	ANIM_TAG_RED_HEART,
	ANIM_TAG_RED_ORB,
	ANIM_TAG_EYE_SPARKLE,
	ANIM_TAG_PINK_HEART,
	ANIM_TAG_ANGEL,
	ANIM_TAG_DEVIL,
	ANIM_TAG_SWIPE,
	ANIM_TAG_ROOTS,
	ANIM_TAG_ITEM_BAG,
	ANIM_TAG_JAGGED_MUSIC_NOTE,
	ANIM_TAG_POKEBALL,
	ANIM_TAG_SPOTLIGHT,
	ANIM_TAG_LETTER_Z,
	ANIM_TAG_RAPID_SPIN,
	ANIM_TAG_TRI_FORCE_TRIANGLE,
	ANIM_TAG_WISP_ORB,
	ANIM_TAG_WISP_FIRE,
	ANIM_TAG_GOLD_STARS,
	ANIM_TAG_ECLIPSING_ORB,
	ANIM_TAG_GRAY_ORB,
	ANIM_TAG_BLUE_ORB,
	ANIM_TAG_RED_ORB_2,
	ANIM_TAG_PINK_PETAL,
	ANIM_TAG_PAIN_SPLIT,
	ANIM_TAG_CONFETTI,
	ANIM_TAG_GREEN_STAR,
	ANIM_TAG_PINK_CLOUD,
	ANIM_TAG_SWEAT_DROP,
	ANIM_TAG_GUARD_RING,
	ANIM_TAG_PURPLE_SCRATCH,
	ANIM_TAG_PURPLE_SWIPE,
	ANIM_TAG_TAG_HAND,
	ANIM_TAG_SMALL_RED_EYE,
	ANIM_TAG_HOLLOW_ORB,
	ANIM_TAG_X_SIGN,
	ANIM_TAG_BLUEGREEN_ORB,
	ANIM_TAG_PAW_PRINT,
	ANIM_TAG_PURPLE_FLAME,
	ANIM_TAG_RED_BALL,
	ANIM_TAG_SMELLINGSALT_EFFECT,
	ANIM_TAG_METEOR,
	ANIM_TAG_FLAT_ROCK,
	ANIM_TAG_MAGNIFYING_GLASS,
	ANIM_TAG_BROWN_ORB,
	ANIM_TAG_METAL_SOUND_WAVES,
	ANIM_TAG_FLYING_DIRT,
	ANIM_TAG_ICICLE_SPEAR,
	ANIM_TAG_HAIL,
	ANIM_TAG_GLOWY_RED_ORB,
	ANIM_TAG_GLOWY_GREEN_ORB,
	ANIM_TAG_GREEN_SPIKE,
	ANIM_TAG_WHITE_CIRCLE_OF_LIGHT,
	ANIM_TAG_GLOWY_BLUE_ORB,
	ANIM_TAG_UNUSED_RED_BRICK,
	ANIM_TAG_WHITE_FEATHER,
	ANIM_TAG_SPARKLE_6,
	ANIM_TAG_SPLASH,
	ANIM_TAG_SWEAT_BEAD,
	ANIM_TAG_UNUSED_GEM_1,
	ANIM_TAG_UNUSED_GEM_2,
	ANIM_TAG_UNUSED_GEM_3,
	ANIM_TAG_SLAM_HIT_2,
	ANIM_TAG_RECYCLE,
	ANIM_TAG_UNUSED_RED_PARTICLES,
	ANIM_TAG_PROTECT,
	ANIM_TAG_DIRT_MOUND,
	ANIM_TAG_SHOCK_3,
	ANIM_TAG_WEATHER_BALL,
	ANIM_TAG_BIRD,
	ANIM_TAG_CROSS_IMPACT,
	ANIM_TAG_SLASH_2,
	ANIM_TAG_WHIP_HIT,
	ANIM_TAG_BLUE_RING_2,
	MAX_ANIM_TAG
};

enum /* anim_battler */
{
	ANIM_BATTLER_ATTACKER,
	ANIM_BATTLER_TARGET,
	ANIM_BATTLER_ATK_PARTNER,
	ANIM_BATTLER_DEF_PARTNER
};

/* stereo panning constants [0-255]
 *
 *          0
 *         .  .
 *      .        .
 * 192 .          . 63
 *     .          .
 *      .        .
 *         .  .
 *          127
 */

enum
{
	SOUND_PAN_TARGET = 63
};

enum
{
	SOUND_PAN_ATTACKER = 192
};

enum
{
	SOUND_PAN_ATTACKER_NEG = -64
};

/* move background IDs */

enum /* movebg */
{
	MOVEBG_DARK_,
	MOVEBG_DARK,
	MOVEBG_GHOST,
	MOVEBG_PSYCHIC,
	MOVEBG_IMPACT_OPPONENT,
	MOVEBG_IMPACT_PLAYER,
	MOVEBG_IMPACT_CONTESTS,
	MOVEBG_DRILL,
	MOVEBG_DRILL_CONTESTS,
	MOVEBG_HIGHSPEED_OPPONENT,
	MOVEBG_HIGHSPEED_PLAYER,
	MOVEBG_THUNDER,
	MOVEBG_GUILLOTINE_OPPONENT,
	MOVEBG_GUILLOTINE_PLAYER,
	MOVEBG_GUILLOTINE_CONTESTS,
	MOVEBG_ICE,
	MOVEBG_COSMIC,
	MOVEBG_SEISMICTOSS_SKUUPPERCUT,
	MOVEBG_FLYING,
	MOVEBG_FLYING_CONTESTS,
	MOVEBG_AURORABEAM,
	MOVEBG_FISSURE,
	MOVEBG_BUG_OPPONENT,
	MOVEBG_BUG_PLAYER,
	MOVEBG_SOLARBEAM_OPPONENT,
	MOVEBG_SOLARBEAM_PLAYER,
	MOVEBG_SOLARBEAM_CONTESTS,
	MAX_MOVEBG
};

/* general animations table */
enum /* b_anim */
{
	B_ANIM_CASTFORM_CHANGE,
	B_ANIM_STATS_CHANGE,
	B_ANIM_SUBSTITUTE_FADE,
	B_ANIM_SUBSTITUTE_APPEAR,
	B_ANIM_POKEBLOCK_THROW,
	B_ANIM_ITEM_KNOCKOFF,
	B_ANIM_TURN_TRAP,
	B_ANIM_ITEM_EFFECT,
	B_ANIM_SMOKEBALL_ESCAPE,
	B_ANIM_HANGED_ON,
	B_ANIM_RAIN_CONTINUES,
	B_ANIM_SUN_CONTINUES,
	B_ANIM_SANDSTORM_CONTINUES,
	B_ANIM_HAIL_CONTINUES,
	B_ANIM_LEECH_SEED_DRAIN,
	B_ANIM_MON_HIT,
	B_ANIM_ITEM_STEAL,
	B_ANIM_SNATCH_MOVE,
	B_ANIM_FUTURE_SIGHT_HIT,
	B_ANIM_DOOM_DESIRE_HIT,
	B_ANIM_FOCUS_PUNCH_SETUP,
	B_ANIM_INGRAIN_HEAL,
	B_ANIM_WISH_HEAL
};

/* special animations table */
enum /* b_anim */
{
	B_ANIM_LVL_UP,
	B_ANIM_SWITCH_OUT_PLAYER_MON,
	B_ANIM_SWITCH_OUT_OPPONENT_MON,
	B_ANIM_BALL_THROW,
	B_ANIM_SAFARI_BALL_THROW,
	B_ANIM_SUBSTITUTE_TO_MON,
	B_ANIM_MON_TO_SUBSTITUTE
};

/* status animations table */
enum /* b_anim */
{
	B_ANIM_STATUS_PSN,
	B_ANIM_STATUS_CONFUSION,
	B_ANIM_STATUS_BRN,
	B_ANIM_STATUS_INFATUATION,
	B_ANIM_STATUS_SLP,
	B_ANIM_STATUS_PRZ,
	B_ANIM_STATUS_FRZ,
	B_ANIM_STATUS_CURSED,
	B_ANIM_STATUS_NIGHTMARE,
	/* NOTE: Does not actually exist */
	B_ANIM_STATUS_WRAPPED
};

/* Trapping Wrap-like moves’ end-turn animations table */
enum /* trap_anim */
{
	TRAP_ANIM_BIND_WRAP,
	TRAP_ANIM_FIRE_SPIN,
	TRAP_ANIM_WHIRLPOOL,
	TRAP_ANIM_CLAMP,
	TRAP_ANIM_SAND_TOMB
};

/* Weather definitions; used in battle animation scripts */
enum /* weather_anim */
{
	ANIM_WEATHER_NONE,
	ANIM_WEATHER_SUN,
	ANIM_WEATHER_RAIN,
	ANIM_WEATHER_SANDSTORM,
	ANIM_WEATHER_HAIL
};

#endif /* INC__CONST_BATTLE_ANIM_H */
